### ISSUE TITLE
Timer runs in the negative range

### ISSUE THREAD

**Issue by HappylabWien** [OllisGit/OctoPrint-AutoLogout#1]
When you're not logged in, the countdown timer runs into negativ range (see screenshot).
![image](https://user-images.githubusercontent.com/33063755/68212333-9b4cd280-ffd9-11e9-9e4b-5996edf8c85e.png)

**Comment by OllisGit** [comment]
Hi @HappylabWien ,

what version of OctoPrint do you use?

I released a new Version (1.0.1) that should fix the reported issue.

Please test and give a feedback.

Thx, in advance
Olli

**Comment by HappylabWien** [comment]
I use OctoPrint 1.3.12 running on OctoPi 0.16.0 and Version 1.0.1 of the AutoLogout plugin.
When I open OctoPrint in the browser it looks good. I'm not logged in and there is no count down:
![image](https://user-images.githubusercontent.com/33063755/68314395-62366000-00b6-11ea-8bb4-4fabf1ab2653.png)

The countdown starts, when I'm logged in, thats also fine:
![image](https://user-images.githubusercontent.com/33063755/68314627-c22d0680-00b6-11ea-92f3-cdf48477a306.png)

BUT: When I log out again, it stills shows the timer (which eventually runs into negative range):
![image](https://user-images.githubusercontent.com/33063755/68314779-0ae4bf80-00b7-11ea-85c4-81c09cae9b12.png)

**Comment by OllisGit** [comment]
Hi @HappylabWien ,

I couldn't reproduce the error on my V1.3.11. Opening the browser (with logout user) I received a new login form:
![image](https://user-images.githubusercontent.com/24205767/68326294-691b9d80-00cb-11ea-8d09-0f7617620a72.png)

I thought it is related to the old octoprint version, but now I realized that you probably disabled the standard "Force Login"-Plugin, right?

I fixed this issue in the newest version 1.0.2, please test and give feedback.
Thx,
Olli

**Comment by HappylabWien** [comment]
Hi Olli,
You're right, I have disabled the Force Login plugin. I just wanted to update AutoLogout via the Software Update Feature in OctoPrint, but it says that everyting is up to date (but it is still 1.0.1). 
Any idea why?

Roland

**Comment by OllisGit** [comment]
@HappylabWien I double checked the release-zip and the zip includes the newest version (see setup.py). 
Maybe it is a caching problem. Did you already try to force an update check, like this:
![image](https://user-images.githubusercontent.com/24205767/68396845-7e97d280-0172-11ea-9b5c-838cebebfef1.png)
If this also not working, then just uninstall the plugin, restart the server and download the latest version via Plugin-Manager. This should definitely work!

**Comment by HappylabWien** [comment]
Great, thanks! Now it works!
