### ISSUE TITLE
Feature Request: Logout on job complete

### ISSUE THREAD

**Issue by gcurtis79** [OllisGit/OctoPrint-AutoLogout#2]
Would it be possible to add an "On Job Compete" option instead of a timer?

We have several printers at our Makerspace, and I have a specific user account for Cura Slicer to upload files, but each user needs to log into the printer's web interface to actually start the print. With an option like this, the user that started the print could stay logged in throughout the entire print, in case a change or stop is needed. The user would automatically be logged out after the print completes to allow the next user to use the printer.

I might take a stab at forking and seeing if I can add it myself, but thought I'd ask always.

Thanks.

**Comment by OllisGit** [comment]
HI @gcurtis79,

just to make sure: 
- Logout only after a successful print
- Should it be delayed/canceled logout or a hard logout? 

BR
Olli

**Comment by OllisGit** [comment]
Hi @gcurtis79,
new version is out (V1.2.0) and include this feature.

Please test and give feedback.
Thx, in advance
Olli
